/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailIdRouteImport } from './routes/email.$id'
import { Route as ApiRealtimeRouteImport } from './routes/api.realtime'
import { Route as ApiAuthStartRouteImport } from './routes/api.auth.start'
import { Route as ApiAuthCallbackRouteImport } from './routes/api.auth.callback'

const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailIdRoute = EmailIdRouteImport.update({
  id: '/email/$id',
  path: '/email/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRealtimeRoute = ApiRealtimeRouteImport.update({
  id: '/api/realtime',
  path: '/api/realtime',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthStartRoute = ApiAuthStartRouteImport.update({
  id: '/api/auth/start',
  path: '/api/auth/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRoute
  '/api/realtime': typeof ApiRealtimeRoute
  '/email/$id': typeof EmailIdRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/start': typeof ApiAuthStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRoute
  '/api/realtime': typeof ApiRealtimeRoute
  '/email/$id': typeof EmailIdRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/start': typeof ApiAuthStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRoute
  '/api/realtime': typeof ApiRealtimeRoute
  '/email/$id': typeof EmailIdRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/start': typeof ApiAuthStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacts'
    | '/api/realtime'
    | '/email/$id'
    | '/api/auth/callback'
    | '/api/auth/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacts'
    | '/api/realtime'
    | '/email/$id'
    | '/api/auth/callback'
    | '/api/auth/start'
  id:
    | '__root__'
    | '/'
    | '/contacts'
    | '/api/realtime'
    | '/email/$id'
    | '/api/auth/callback'
    | '/api/auth/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactsRoute: typeof ContactsRoute
  ApiRealtimeRoute: typeof ApiRealtimeRoute
  EmailIdRoute: typeof EmailIdRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthStartRoute: typeof ApiAuthStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/$id': {
      id: '/email/$id'
      path: '/email/$id'
      fullPath: '/email/$id'
      preLoaderRoute: typeof EmailIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/realtime': {
      id: '/api/realtime'
      path: '/api/realtime'
      fullPath: '/api/realtime'
      preLoaderRoute: typeof ApiRealtimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/start': {
      id: '/api/auth/start'
      path: '/api/auth/start'
      fullPath: '/api/auth/start'
      preLoaderRoute: typeof ApiAuthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactsRoute: ContactsRoute,
  ApiRealtimeRoute: ApiRealtimeRoute,
  EmailIdRoute: EmailIdRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthStartRoute: ApiAuthStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
