export {
  createOAuth2Client,
  exchangeCodeForTokens,
  getAuthUrl,
  isAuthenticated,
} from "./auth.ts";

export {
  addLabels,
  cacheBody,
  cacheBodyBatch,
  countMessages,
  getCachedBody,
  getDb,
  getLabelNameMap,
  getLabels,
  getMessageById,
  getSyncState,
  queryThreads,
  removeLabels,
  resolveLabelName,
  resolveShortId,
  saveIdMap,
  saveLastList,
  searchMessages,
  setSyncState,
  storedToSummary,
  type CountOpts,
  type SearchOpts,
  type SearchResult,
  type StoredMessage,
  type SyncState,
  type ThreadQueryOpts,
  type ThreadResult,
} from "./db.ts";

export {
  buildSinceQuery,
  incrementalSync,
  initialSync,
  shouldAutoSync,
} from "./sync.ts";

export {
  createDraft,
  createLabel,
  createReplyDraft,
  downloadAttachment,
  addToInbox,
  getEmail,
  getHistory,
  getMessageFull,
  markAsRead,
  markAsUnread,
  removeFromInbox,
  getMessageMetadata,
  getProfile,
  getThread,
  modifyLabels,
  sendMessage,
  sendReply,
  searchEmails,
  searchThreads,
  type AttachmentInfo,
  type DraftOptions,
  type DraftResult,
  type EmailSummary,
  type HistoryEvent,
  type ParsedMessageFull,
  type ParsedMessageMetadata,
  type ReplyDraftOptions,
  type SendResult,
} from "./gmail.ts";

export { parseGmailQuery, type ParsedQuery } from "./query.ts";
