export {
  createOAuth2Client,
  credentialsConfigured,
  exchangeCodeForTokens,
  exchangeCodeForTokensWithRedirect,
  getAuthUrl,
  getAuthUrlForRedirect,
  isAuthenticated,
} from "./auth.ts";

export {
  addLabels,
  addThreadLabels,
  cacheBody,
  cacheBodyBatch,
  countMessages,
  deleteLabel as deleteStoredLabel,
  getCachedBody,
  getDb,
  getLabelNameMap,
  getLabels,
  getMessageById,
  getSyncState,
  insertMessageBatch,
  queryThreads,
  removeLabels,
  removeThreadLabels,
  resolveLabelName,
  resolveShortId,
  saveIdMap,
  saveLastList,
  searchMessages,
  setSyncState,
  storedToSummary,
  queryContacts,
  upsertLabels,
  updateLabel as updateStoredLabel,
  type ContactQueryOpts,
  type ContactRow,
  type ContactSortField,
  type CountOpts,
  type SearchOpts,
  type SearchResult,
  type StoredMessage,
  type SyncState,
  type ThreadQueryOpts,
  type ThreadResult,
} from "./db.ts";

export {
  buildSinceQuery,
  incrementalSync,
  initialSync,
  shouldAutoSync,
} from "./sync.ts";

export {
  createDraft,
  createFilter,
  deleteFilter,
  deleteLabel,
  createLabel,
  createReplyDraft,
  downloadAttachment,
  addToInbox,
  addThreadToInbox,
  getEmail,
  getFilter,
  getHistory,
  getMessageFull,
  listFilters,
  markAsRead,
  markAsUnread,
  removeFromInbox,
  removeThreadFromInbox,
  getMessageMetadata,
  getProfile,
  getThread,
  modifyLabels,
  modifyThreadLabels,
  sendMessage,
  sendReply,
  searchEmails,
  searchThreads,
  updateLabel,
  type AttachmentInfo,
  type DraftOptions,
  type DraftResult,
  type EmailSummary,
  type FilterAction,
  type FilterCriteria,
  type GmailFilter,
  type HistoryEvent,
  type ParsedMessageFull,
  type ParsedMessageMetadata,
  type ReplyDraftOptions,
  type SendResult,
} from "./gmail.ts";

export { parseGmailQuery, type ParsedQuery } from "./query.ts";

export {
  emitStateChange,
  subscribeStateChanges,
  type StateChangeEvent,
  type StateChangeKind,
} from "./realtime.ts";
